name: Deploy Vite + React to GitHub Pages

on:
  push:
    branches:
      - main  # Ajusta la rama principal si no es "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Ajusta la versión de Node.js si es necesario

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Genera la carpeta dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          name: github-pages  # Subir solo un artefacto con este nombre
          path: dist  # Ruta de salida del build
      - name: Delete old artifacts
        uses: geekyeggo/delete-artifact@v2
        with:
          name: github-pages

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
